### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by cst781** [gentaiscool/end2end-asr-pytorch#12]
hello, could you tell what is your best WER in libirspeech data？i got the result of 17% CER ,33 % WER on test dataset, it is far from the result on validation dataset-25% WER

**Comment by gentaiscool** [comment]
I think it is normal to get higher WER on the testset. Did you train with all librispeech data? and we might be able to run beam search to get lower WER.

**Comment by cst781** [comment]
I trained it on the full train dataset，so it means that you also haven't got the optimal result and still need some improvement for lower wer or cer？发自我的iPhone------------------ Original ------------------From: Genta Indra Winata  <notifications@github.com>Date: Wed,Jul 10,2019 8:18 PMTo: gentaiscool/end2end-asr-pytorch <end2end-asr-pytorch@noreply.github.com>Cc: cst781 <stchen0828@gmail.com>, Author <author@noreply.github.com>Subject: Re: [gentaiscool/end2end-asr-pytorch] about the result (#12)I think it is normal to get higher WER on the testset. Did you train with all librispeech data? and we might be able to run beam search to get lower WER.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHF2WKFER4SRPASG52UTP6XHSJA5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZTIXPY#issuecomment-510036927",
"url": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHF2WKFER4SRPASG52UTP6XHSJA5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZTIXPY#issuecomment-510036927",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gentaiscool** [comment]
Currently, I am still working on other task, but I will try to find the optimal solution on librispeech soon. The configuration that I posted in the repository, it is for AiShell-1. To improve the performance, you need to tune the embedding size (the vocab in librispeech << AiShell-1) and number of layers.

**Comment by cst781** [comment]
ok，i will take a try发自我的iPhone------------------ Original ------------------From: Genta Indra Winata  <notifications@github.com>Date: Thu,Jul 11,2019 0:51 AMTo: gentaiscool/end2end-asr-pytorch <end2end-asr-pytorch@noreply.github.com>Cc: cst781 <stchen0828@gmail.com>, Author <author@noreply.github.com>Subject: Re: [gentaiscool/end2end-asr-pytorch] about the result (#12)Currently, I am still working on other task, but I will try to find the optimal solution on librispeech soon. The configuration that I posted in the repository, it is for AiShell-1. To improve the performance, you need to tune the embedding size (the vocab in librispeech << AiShell-1) and number of layers.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHFYCT7D2YDKLOU2MLPDP6YHQRA5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZUCMMQ#issuecomment-510142002",
"url": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHFYCT7D2YDKLOU2MLPDP6YHQRA5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZUCMMQ#issuecomment-510142002",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gentaiscool** [comment]
I will close this issue

**Comment by ArtemisZGL** [comment]
@cst781 hello, do you find the optimal solution?

**Comment by cst781** [comment]
get a not very good result，maybe not the optimal发自我的iPhone------------------ Original ------------------From: ArtemisZGL  <notifications@github.com>Date: Mon,Feb 17,2020 9:11 PMTo: gentaiscool/end2end-asr-pytorch <end2end-asr-pytorch@noreply.github.com>Cc: cst781 <stchen0828@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [gentaiscool/end2end-asr-pytorch] about the result (#12)@cst781 hello, do you find the optimal solution?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHF5ALLRYNWOH64CP2RTRDM7V5A5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMAJEPQ#issuecomment-587239998",
"url": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHF5ALLRYNWOH64CP2RTRDM7V5A5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMAJEPQ#issuecomment-587239998",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ArtemisZGL** [comment]
@cst781 do you use the test.py to test the result ? cause i use librispeech 100 to train the model and get a very bad result when using greedy search(all  the prediction str is almost the same), and i found the encoder output tensor is strange.

**Comment by cst781** [comment]
you need to debug some code，after that，the result is also not very good发自我的iPhone------------------ Original ------------------From: ArtemisZGL  <notifications@github.com>Date: Mon,Feb 24,2020 1:14 AMTo: gentaiscool/end2end-asr-pytorch <end2end-asr-pytorch@noreply.github.com>Cc: cst781 <stchen0828@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [gentaiscool/end2end-asr-pytorch] about the result (#12)@cst781 do you use the test.py to test the result ? cause i use librispeech 100 to train the model and get a very bad result when using greedy search(all  the prediction str is almost the same), and i found the encoder output tensor is strange.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHFYKUU7KDHKJROFHXYTRENQVFA5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMWXBDA#issuecomment-590180492",
"url": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHFYKUU7KDHKJROFHXYTRENQVFA5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMWXBDA#issuecomment-590180492",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ArtemisZGL** [comment]
@cst781 thanks, cound you please give me some tips about where should be modified, cause i use the 100h librispeech result is queit bad, the encoder seems not learn anything.

**Comment by cst781** [comment]
you can refer to the comment by LeighSu，which may help you solve the problem发自我的iPhone------------------ Original ------------------From: ArtemisZGL  <notifications@github.com>Date: Mon,Feb 24,2020 5:08 AMTo: gentaiscool/end2end-asr-pytorch <end2end-asr-pytorch@noreply.github.com>Cc: cst781 <stchen0828@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [gentaiscool/end2end-asr-pytorch] about the result (#12)@cst781 thanks, cound you please give me some tips about where should be modified, cause i use the 100h librispeech result is queit bad, the encoder seems not learn anything.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHF44KJROZQM7VEEUGWLREOMBXA5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMXHKDA#issuecomment-590247180",
"url": "https://github.com/gentaiscool/end2end-asr-pytorch/issues/12?email_source=notifications\u0026email_token=ALNPHF44KJROZQM7VEEUGWLREOMBXA5CNFSM4H7KZ2KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMXHKDA#issuecomment-590247180",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
