### ISSUE TITLE
Train my own dataset for a different language 

### ISSUE THREAD

**Issue by jafarOlamide** [gentaiscool/end2end-asr-pytorch#15]

**Comment by jafarOlamide** [comment]
I want to train my dataset for a different language (Yoruba), it is also a tonal language.

**Comment by gentaiscool** [comment]
HI @jafarOlamide, it should work. I ran the model with Chinese, also a tonal language. You can use all Yoruba characters as the vocabulary. Please let me know if you have another questions.

**Comment by jafarOlamide** [comment]
so I tried training the model on Google colab and I got the following results. But got interrupted, see the image to get a picture of what I'm painting
![Screenshot from 2019-11-27 05-14-42](https://user-images.githubusercontent.com/31123468/69693785-e046bf00-10d6-11ea-9457-28a974ec56bc.png)

**Comment by jafarOlamide** [comment]
Can you also provide further research papers and articles to better understand the transformer model. Thank you.

**Comment by gentaiscool** [comment]
You can check the following papers:
- Winata, G. I., Madotto, A., Wu, C. S., & Fung, P. (2019). Code-Switched Language Models Using Neural Based Synthetic Data from Parallel Sentences. In Proceedings of the 23rd Conference on Computational Natural Language Learning (CoNLL) (pp. 271-280).
- Winata, G. I., Cahyawijaya, S., Lin, Z., Liu, Z., & Fung, P. (2019). Lightweight and Efficient End-to-End Speech Recognition Using Low-Rank Transformer. arXiv preprint arXiv:1910.13923.
- Zhou, S., Dong, L., Xu, S., & Xu, B. (2018). Syllable-based sequence-to-sequence speech recognition with the transformer in mandarin chinese. arXiv preprint arXiv:1804.10752.
