### ISSUE TITLE
Version of Pytorch.

### ISSUE THREAD

**Issue by jafarOlamide** [gentaiscool/end2end-asr-pytorch#16]
Hello, I want to train my dataset on google colab. Can the latest version of Pytorch be used ??

**Comment by gentaiscool** [comment]
Hi @jafarOlamide. Are you going to run in PyTorch 1.3? I think the code can support that version, specifically for the single GPU case.

**Comment by jafarOlamide** [comment]
Alright, thanks very much @gentaiscool
