### ISSUE TITLE
Convert text data into label file

### ISSUE THREAD

**Issue by aiscientist** [gentaiscool/end2end-asr-pytorch#18]
Hi, do you have any converter for converting all the text data into json file for label?

Thanks,

**Comment by gentaiscool** [comment]
hi @aiscientist, I will add the script soon to the repo. Thanks for the suggestion!

**Comment by gentaiscool** [comment]
@aiscientist for the meantime, you can use the following snippet:
**labels** is a list of characters.

```
with open("labels.json", "w+") as labels_json:
    labels_json.write("[")
    i = 0
    labels_json.write('\n"_"')
    for char in labels:
        if char == "_" or char == " ":
            continue
        labels_json.write(',\n')
        
        if char == "\\":
            print("slash")
            labels_json.write('"')
            labels_json.write('\\')
            labels_json.write('\\')
            labels_json.write('"')
        elif char == '"':
            print('double quote', i, char)
            labels_json.write('"\\""')
        else:
            labels_json.write('"' + char + '"')

        i += 1
    labels_json.write(',\n" "\n]')`

**Comment by SamuelCahyawijaya** [comment]
I implemented `generate_label_from_corpora()` function to generate character labels given file / folder path(s), and output the result into a json file.

https://github.com/gentaiscool/end2end-asr-pytorch/commit/5d4c1f42197bc7d38e94c49b896d37203bf9495e

**Comment by aiscientist** [comment]
@SamuelCahyawijaya Thanks for your support!
