### ISSUE TITLE
BREAK IN TRAINING CUSTOM DATASET 

### ISSUE THREAD

**Issue by jafarOlamide** [gentaiscool/end2end-asr-pytorch#19]
Please reopen issue #17 . Thanks, had a typographical error earlier, still getting the same error with the training on colab.

**Comment by gentaiscool** [comment]
did you change **collate_fn** function?

**Comment by jafarOlamide** [comment]
I did not but I'll check to confirm

**Comment by SamuelCahyawijaya** [comment]
@jafarOlamide : We have reopened issue #17, I'll close this issue and we can continue the discussion from there.
