### ISSUE TITLE
Problem in Training on multi-gpu

### ISSUE THREAD

**Issue by paanguin** [gentaiscool/end2end-asr-pytorch#24]
I saw you fixed an issue at https://github.com/gentaiscool/end2end-asr-pytorch/issues/6, and I think this is not my problem.

I slightly fixed your code at the data loading for my convenience. Instead of using labels as separated files, I changed it to use a long list file.

Anyway, the problem appeared in the multi-gpu training.

The following training code with a single device (gpu) did not caused any problems.

> CUDA_VISIBLE_DEVICES=0 python train.py --train-manifest-list ~/asr/data/librispeech/libri_asis --valid-manifest-list ~/asr/data/librispeech/libri_dev --test-manifest-list ~/asr/data/librispeech/libri_test_clean --labels-path data/labels/labels.json --cuda --device-ids 0 --parallel --save-every 1 --save-folder train_models/librispeech_transformer --name librispeech_transformer --warmup 8000 --epochs 10 --label-smoothing 0.15 --window-size 0.025 --window-stride 0.01 --window hann --lr 0.1 --feat_extractor None --num-layers 6 --dropout 0.2 --dim-inner 2048 --num-heads 8 --dim-input 201 --batch-size 4

However, when I run it with multiple gpus, I got error messages.

Here is the command,
> CUDA_VISIBLE_DEVICES=0,1 python train.py --train-manifest-list ~/asr/data/librispeech/libri_asis --valid-manifest-list ~/asr/data/librispeech/libri_dev --test-manifest-list ~/asr/data/librispeech/libri_test_clean --labels-path data/labels/labels.json --cuda --device-ids 0 1 --parallel --save-every 1 --save-folder train_models/librispeech_transformer --name librispeech_transformer --warmup 8000 --epochs 10 --label-smoothing 0.15 --window-size 0.025 --window-stride 0.01 --window hann --lr 0.1 --feat_extractor None --num-layers 6 --dropout 0.2 --dim-inner 2048 --num-heads 8 --dim-input 201 --batch-size 8

and this is the error messages.

> ==================================================
THE EXPERIMENT LOG IS SAVED IN: log/librispeech_transformer
TRAINING MANIFEST:  ['/home/hh1208-kang/asr/data/librispeech/libri_asis']
VALID MANIFEST:  ['/home/hh1208-kang/asr/data/librispeech/libri_dev']
TEST MANIFEST:  ['/home/hh1208-kang/asr/data/librispeech/libri_test_clean']
==================================================
the model is initialized without feature extractor
load with device_ids [0, 1]
  0%|                                                                                                                                                        | 0/35156 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 117, in <module>
    trainer.train(model, train_loader, train_sampler, valid_loader_list, opt, loss_type, start_epoch, num_epochs, label2id, id2label, metrics)
  File "/home/hh1208-kang/end2end-asr-pytorch/trainer/asr/trainer.py", line 59, in train
    src, src_lengths, tgt, verbose=False)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hh1208-kang/end2end-asr-pytorch/utils/parallel.py", line 147, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/hh1208-kang/end2end-asr-pytorch/utils/parallel.py", line 190, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hh1208-kang/end2end-asr-pytorch/utils/parallel.py", line 146, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/hh1208-kang/end2end-asr-pytorch/utils/parallel.py", line 184, in replicate
    return replicate(module, device_ids)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/parallel/replicate.py", line 88, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/parallel/_functions.py", line 21, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/cuda/comm.py", line 39, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: all tensors must be on devices[0]

My machine have 4 GTX TITAN GPUs. I'll be very grateful if you would give any suggestions or advises for me to solve this problem.

**Comment by gentaiscool** [comment]
thanks for the report. I am going to check the code.

**Comment by xiechen0692** [comment]
**Hi, I also have same problem. When model is training, there is no error. but the mistake shows up in validation:**
'TypeError: Caught TypeError in replica 2 on device 2.
TypeError: forward() missing 3 required positional arguments: 'padded_input', 'input_lengths', and 'padded_target''

**Then, I change the validation code in 'trainer.py' using your code with parallel class:**
'pred, gold, hyp_seq, gold_seq = data_parallel(model, inputs= (src, src_lengths, tgt),device_ids=[0, 1, 2])'
**But new mistake shows up:**
'    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: all tensors must be on devices[0]
'
Looks similar with paanguin. Can you tell me how to solve this problem? Thanks a lot!

**Comment by aiscientist** [comment]
Same error here with 

    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: all tensors must be on devices[0]

**Comment by SamuelCahyawijaya** [comment]
@paanguin @aiscientist : We have figured out the issue, we are currently fixing the code. We will get back into you in few days.

**Comment by gentaiscool** [comment]
@aiscientist @paanguin we have pushed the correction to develop branch. We will review the code and merge the branch to the master soon.

**Comment by SamuelCahyawijaya** [comment]
@aiscientist @paanguin  we have updated the code on `master` branch, kindly pull the latest code on `master branch.

**Comment by paanguin** [comment]
I merged your code on master `branch`, however, I got another error with multi-gpu running.

I tried to reproduce the error with a toy example. It seems to be related to the batch size and number of GPUs. I made a data list files that each contains 10 examples each. I ran the example with 4 GPUs with batch size 8.

> python train.py --train-manifest-list ~/asr/data/librispeech/libri_asis_10 --valid-manifest-list ~/asr/data/librispeech/libri_dev_10 --test-manifest-list ~/asr/data/librispeech/libri_test_clean --labels-path data/labels/labels.json --cuda --save-every 1 --save-folder trained_models/ --name librispeech_drop0.1_cnn_batch12_4_vgg_layer4_lr0.1 --epochs 10 --cuda --batch-size 8 --lr 0.1 --save-folder save/ --save-every 1 --feat_extractor vgg_cnn --dropout 0.1 --num-layers 4 --num-heads 8 --dim-model 512 --dim-key 64 --dim-value 64 --dim-input 161 --dim-inner 2048 --dim-emb 512 --shuffle --min-lr 1e-6 --k-lr 1 --parallel --device-ids 0 1 2 3

And I encountered the following error. The same error appeared when the batch size is not a multiple of the number of GPUs. For example, when the batch size is set to 6 while the number of GPUs are 4, the error occurs. In the following run, it seems that then the device 2 does not have any examples in the last batch, since the number of the remaining examples at the last batch is 2 but the number of GPUs are 4. At this time, the device 0 and 1 seems to have the example, while the device 2 and device 3 do not. I think this is natural situation, however, yet the program made the error. 

I hope to know whether this error appears on your versions of codes or not. I'm suspicious that if I made some mistakes in the merging your codes into my own version of codes.

> ==================================================
THE EXPERIMENT LOG IS SAVED IN: log/librispeech_drop0.1_cnn_batch12_4_vgg_layer4_lr0.1
TRAINING MANIFEST:  ['/home/hh1208-kang/asr/data/librispeech/libri_asis_10']
VALID MANIFEST:  ['/home/hh1208-kang/asr/data/librispeech/libri_dev_10']
TEST MANIFEST:  ['/home/hh1208-kang/asr/data/librispeech/libri_test_clean']
==================================================

load with device_ids [0, 1, 2, 3]
(Epoch 1) TRAIN LOSS:4.3495 CER:96.68% LR:0.0000010:  50%|███████████████████████████████████████████████                                               | 1/2 [00:09<00:09,  9.41s/it]Traceback (most recent call last):
  File "train.py", line 116, in <module>
    trainer.train(model, train_loader, train_sampler, valid_loader_list, opt, loss_type, start_epoch, num_epochs, label2id, id2label, metrics)
  File "/home/hh1208-kang/end2end-asr-pytorch-user/trainer/asr/trainer.py", line 58, in train
    pred, gold, hyp_seq, gold_seq = model(src, src_lengths, tgt, verbose=False)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 2 on device 2.
Original Traceback (most recent call last):
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/hh1208-kang/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 3 required positional arguments: 'padded_input', 'input_lengths', and 'padded_target'
