### ISSUE TITLE
Question about WER and feature extraction

### ISSUE THREAD

**Issue by xiechen0692** [gentaiscool/end2end-asr-pytorch#25]
First thanks for opening source!  Here are two questions:
What WER or CER can your model achieve for Librispeech and how many epochs it needs?
Why don't you use fbank feature as input?

**Comment by gentaiscool** [comment]
Thanks for your interest in our work @xiechen0692. We have tested our model in AiShell and achieved 13.5% CER using a beam search with a beam width of 5. We can still improve the model by increasing the beam width and incorporate an external LM, fine-tune the hyperparameters. 

Regarding to your question on fbank feature, in this paper we follow the implementation of spectrogram in DeepSpeech2 model and interestingly deep neural models are able to leverage these features very effectively.

We are also interested to incorporate filter bank input in this repo soon.
