### ISSUE TITLE
trainer.py have problem (ZeroDivisionError: division by zero)

### ISSUE THREAD

**Issue by ssteven502tw** [gentaiscool/end2end-asr-pytorch#26]
Hi @gentaiscool , i have problem and entered the following:

python train.py --train-manifest-list data / manifests / libri_train_manifest.csv --valid-manifest-list data / manifests / libri_val_manifest.csv --test-manifest-list data / manifests / libri_test_clean_manifest.csv --cuda- -batch-size 12 --labels-path data / labels / labels.json --lr 1e-4 --name libri_drop0.1_cnn_batch12_4_vgg_layer4 --save-folder save / --save-every 5 --feat_extractor vgg_cnn --dropout 0.1 --num-layers 4 --num-heads 8 --dim-model 512 --dim-key 64 --dim-value 64 --dim-input 161 --dim-inner 2048 --dim-emb 512- shuffle --min-lr 1e-6 --k-lr 1

Got wrong information
Traceback (most recent call last):
File "train.py", line 117, in
trainer.train(model, train_loader, train_sampler, valid_loader_list, opt, loss_type, start_epoch, num_epochs, label2id, id2label, metrics)
File "/data1/ytz109/end2end-asr-pytorch-master/trainer/asr/trainer.py", line 162, in train
total_valid_loss/(i+1), total_valid_cer*100/total_valid_char))
ZeroDivisionError: division by zero

=================================================================
I find total_valid_char = 0
Don't know where the settings are wrong? Thank you

**Comment by SamuelCahyawijaya** [comment]
Hi @ssteven502tw , did you retrieve the librispeech data from executing `python data/librispeech.py`?

**Comment by ssteven502tw** [comment]
Hi @SamuelCahyawijaya ,  Yes i have executed python data/librispeech.py and produced following：

- LibriSpeech_dataset：test_clean、test_other、train、val

- manifests：libri_test_clean_manifest.csv、libri_test_other_manifest.csv、libri_train_manifest.csv、 libri_val_manifest.csv

But don't know what's missing , thanks.

**Comment by SamuelCahyawijaya** [comment]
@ssteven502tw : Ok, I think the problem comes from the uppercased letter inside `labels.json`. We are currently testing the updated code, we will get back into you in few days.

**Comment by SamuelCahyawijaya** [comment]
@ssteven502tw : We have updated the code to `master` branch, we updated the `data/labels/labels.json` to lower case kindly pull the latest code on your local.

**Comment by ssteven502tw** [comment]
ok , thanks.

**Comment by ssteven502tw** [comment]
Hello ~ I encountered problems.I entered "python test.py
--test-manifest-list data / manifests / libri_test_clean_manifest.csv
--cuda --continue_from save / libri_drop0.1_cnn_batch12_4_vgg_layer4 /
epoch_21.th". I get wrong result about *test.py: error: unrecognized
arguments: --continue_from*

   1. How do I set --continue_from? Is it a path or?
   2. Small model parameter values?  --dim-model, --dim-inner, --dim-emb = ?

thanks


Samuel Cahyawijaya <notifications@github.com> 於 2020年2月3日 週一 下午8:50寫道：

**Comment by SamuelCahyawijaya** [comment]
@ssteven502tw : I think that is a different issue, it will be better to write a new issue for this. Anyway, it should be `--continue-from` instead of `--continue_from`.

Commonly we use `--dim-model` equals to`--dim-emb`,`--dim-key` and `--dim-value` equals to `--dim-model` times `--num-heads`. So if you want smaller parameters your can reduce both 
`--dim-model`, `--dim-emb`, and `--num-heads`; and then adjust `--dim-key` and `--dim-value` accordingly. You can set any other value for `--dim-key` and `--dim-value`, but I never see this kind of implementation.

You can also reduce `--dim-inner`, it is the linear layer that comes after the self attention in transformer model.

**Comment by ssteven502tw** [comment]
This is very helpful to me, thank.

從 Windows 10 的郵件傳送

寄件者: Samuel Cahyawijaya
傳送時間: 2020年2月8日 下午 12:29
收件者: gentaiscool/end2end-asr-pytorch
副本: ssteven502tw; Mention
主旨: Re: [gentaiscool/end2end-asr-pytorch] trainer.py have problem(ZeroDivisionError: division by zero) (#26)

@ssteven502tw : I think that is a different issue, it will be better to write a new issue for this. Anyway, it should be --continue-from instead of --continue_from.
Commonly we use --dim-model equals to--dim-emb,--dim-key and --dim-value equals to --dim-model times --num-heads. So if you want smaller parameters your can reduce both
--dim-model, --dim-emb, and --num-heads; and then adjust --dim-key and --dim-value accordingly. You can set any other value for --dim-key and --dim-value, but I never see this kind of implementation.
You can also reduce --dim-inner, it is the linear layer that comes after the self attention in transformer model.

**Comment by ssteven502tw** [comment]
I have some questions for you.

First, whether the low-rank transformer model is not good for longer
english sentence recognition (more than 30 words), I found that the WER is
high, and the test is shown in the following figure.





Second, am I not training enough? or is there any way to improve it?



Thanks

Samuel Cahyawijaya <notifications@github.com> 於 2020年2月8日 週六 下午12:29寫道：

**Comment by SamuelCahyawijaya** [comment]
Hi @ssteven502tw, 
1. I cannot find the figure that you are referring to, can you please resend the image?
2. Have you check the training & validation loss? it could be helpful for deciding when to stop the training

Btw, this question is not related to issue #26, please open a new issue for this discussion. Thank you.
