### ISSUE TITLE
CUDA out of memory when validation

### ISSUE THREAD

**Issue by ArtemisZGL** [gentaiscool/end2end-asr-pytorch#29]
First i want to thanks for your work.  And  I run you code with dataset llibrispeech train 100 as training data, dev clean as validation data using GeForce RTX 2070. After several time OOM error, i set the barch size to 4 and finally can train normally. But after one epoch, i also met the OOM error in validation. So i want to konw if i set the batch size smaller can avoid this problem ? Because i notice that in the librispeech dataset process script, the training data have been  pruned to min/max duration but the validation and test data didn't.  
And I also to konw is there a result for librispeech using this code ? I only saw the aishell result in README.  
Thanks.

**Comment by paanguin** [comment]
I added `with torch.no_grad():` before the validation loop: https://github.com/gentaiscool/end2end-asr-pytorch/blob/a22efdda28f1689206eefb3fedbb56fbcc98a753/trainer/asr/trainer.py#L127, by referencing this documents https://discuss.pytorch.org/t/cuda-error-out-of-memory/28123. I think this reduced the problem for me, but not sure. The test code contains `with torch.no_grad():`, too, https://github.com/gentaiscool/end2end-asr-pytorch/blob/a22efdda28f1689206eefb3fedbb56fbcc98a753/test.py#L31, so I think this might help you.

**Comment by ArtemisZGL** [comment]
@paanguin thanks! i will try this.

**Comment by gentaiscool** [comment]
thanks @paanguin I am closing the issue
