### ISSUE TITLE
problem of training on multi-gpu

### ISSUE THREAD

**Issue by cst781** [gentaiscool/end2end-asr-pytorch#6]
when I train on the multi-gpu, I encountered this problem, could you help me figure it out?
  File "multi_train.py", line 91, in <module>
    trainer.train(model, train_loader, train_sampler, valid_loaders, opt, loss_type, start_epoch, num_epochs, label2id, id2label, metrics, logger)
  File "/asr-data/end2end-asr-pytorch/trainer/asr/multi_trainer.py", line 66, in train
    for x in hyp]) for hyp in hyp_seq]
  File "/asr-data/end2end-asr-pytorch/trainer/asr/multi_trainer.py", line 66, in <listcomp>
    for x in hyp]) for hyp in hyp_seq]
  File "/asr-data/end2end-asr-pytorch/trainer/asr/multi_trainer.py", line 66, in <listcomp>
    for x in hyp]) for hyp in hyp_seq]
KeyError: 72340172838076672

**Comment by gentaiscool** [comment]
I think you need to debug _hyp_seq_ object. Can you check `line 71` in transformer.py?
`hyp_best_scores, hyp_best_ids = torch.topk(pred, 1, dim=2)`

**Comment by cst781** [comment]
yes, I checked the line 71, but i still cannot find the problem. I didnot change anything in transformer.py

**Comment by gentaiscool** [comment]
Can you check the number of labels you have? And also print `hyp_best_ids`

**Comment by cst781** [comment]
I still couldnot find what is wrong with the hyp_seq, your multi_train.py could run your own computer?

**Comment by gentaiscool** [comment]
Oh yes, I found the problem. Currently, I am fixing it and finalizing the repo. I plan to finish it this week and I will update the repo hopefully not later than next week. Thanks @cst781
